export const incomeOptList = [
    'Less than $25,000',
    '$25,000 to $34,999',
    '$35,000 to $49,999',
    '$50,000 to $74,999',
    '$75,000 to $99,999',
    '$100,000 to $149,999',
    '$150,000 to $199,999',
    '$200,000 or more',
];
export const employmentOptList = [
    'Employment status and industry',
    'Community and Social Service Occupations',
    'Computer and Mathematical Occupations',
    'Personal Care and Service Occupations',
    'Protective Service Occupations',
    'Architecture and Engineering Occupations',
    'Healthcare Support Occupations',
    'Business and Financial Operations Occupations',
    'Office and Administrative Support Occupations',
    'Production Occupations',
    'Education, Training, and Library Occupations',
    'Construction and Extraction Occupations',
    'Sales and Related Occupations',
    'Building and Grounds Cleaning and Maintenance Occupations',
    'Food Preparation and Serving Related Occupations',
    'Healthcare Practitioners and Technical Occupations',
    'Legal Occupations',
    'Farming, Fishing, and Forestry Occupations',
    'Life, Physical, and Social Science Occupations',
    'Management Occupations',
    'Arts, Design, Entertainment, Sports, and Media Occupations',
    'Installation, Maintenance, and Repair Occupations',
    'Transportation and Materials Moving Occupations',
];
