import {NgModule} from '@angular/core';

import {
    MatInputModule,
    MatFormFieldModule,
    MatCheckboxModule,
    MatButtonModule,
    MatStepperModule,
    MatSelectModule,
    MatAutocompleteModule,
    MatDialogModule,
    MatSidenavModule,
    MatListModule,
    MatToolbarModule,
    MatMenuModule,
    MatTabsModule,
    MatIconModule,
    MatSnackBarModule,
    MatProgressSpinnerModule,
    MatCardModule,
    MatDatepickerModule,
} from '@angular/material';

@NgModule({
    imports: [
        MatCardModule,
        MatInputModule,
        MatFormFieldModule,
        MatCheckboxModule,
        MatButtonModule,
        MatStepperModule,
        MatSelectModule,
        MatAutocompleteModule,
        MatDialogModule,
        MatSidenavModule,
        MatListModule,
        MatToolbarModule,
        MatMenuModule,
        MatTabsModule,
        MatIconModule,
        MatSnackBarModule,
        MatProgressSpinnerModule,
        MatDatepickerModule,
    ],
    exports: [
        MatCardModule,
        MatInputModule,
        MatFormFieldModule,
        MatCheckboxModule,
        MatButtonModule,
        MatStepperModule,
        MatSelectModule,
        MatAutocompleteModule,
        MatDialogModule,
        MatSidenavModule,
        MatListModule,
        MatToolbarModule,
        MatMenuModule,
        MatTabsModule,
        MatIconModule,
        MatSnackBarModule,
        MatProgressSpinnerModule,
        MatDatepickerModule,
    ],
})
export class MaterialModule {
}
